(defvar *data*)

(defun contains-multiple (n str)
  (some (lambda (c) (= (count c str) n)) str))

(defun difference (a b)
  (reduce #'+ (map 'list (lambda (x y) (if (char= x y) 0 1)) a b)))

(defun remove-difference (a b)
  (map 'string #'identity
       (loop for x across a and y across b
             when (char= x y) collect x)))

;;; Part 1

(defun adv02 ()
  (let ((doubles 0)
        (triples 0))
    (dolist (id *data*)
      (when (contains-multiple 2 id)
        (incf doubles))
      (when (contains-multiple 3 id)
        (incf triples)))
    (* doubles triples)))

;;; Part 2

(defun adv02b ()
  (loop for id in *data*
        for x = (find id *data* :test (lambda (x y) (= (difference x y) 1)))
        when x do (return (remove-difference id x))))

;;; Data

(defparameter *data*
  '("dghfbsyiznoumojleevappwqtr"
    "dghfbsyiznoumkjljevacpmqer"
    "dghfbbyizioumkjlxevacpwdtr"
    "dghfbsesznoumkjlxevacpwqkr"
    "dghfbsynznoumkjlxziacpwqtr"
    "cghfbsyiznjumkjlxevacprqtr"
    "dghfjsyizwoumkjlxevactwqtr"
    "dghfdsyfinoumkjlxevacpwqtr"
    "hghfbsyiznoumkjlxivacpwqtj"
    "dgcfbsyiznoumkjlxevacbuqtr"
    "dghfbsyiznoymnjlxevacpwvtr"
    "dfhfbsyiznoumkulxevacptqtr"
    "dghfasyiznovmkjlxevacpwqnr"
    "dghfbsyihnouikjlxevackwqtr"
    "dghfbayiznolmkjlyevacpwqtr"
    "jghfbsyiznoumnjldevacpwqtr"
    "dhhfbsyuznoumkjlxevakpwqtr"
    "nehfrsyiznoumkjlxevacpwqtr"
    "dghfbsyiznxdmkolxevacpwqtr"
    "dgpfbsyizwlumkjlxevacpwqtr"
    "yghfbsyiznoumkjlsevacpwqtm"
    "dghfssyiznoumkjlxevvcpwqjr"
    "dahfbsyiznoumkjlfevacpwqto"
    "duhfcsyiznouvkjlxevacpwqtr"
    "dghfbvyiznoumkjlrevacpwvtr"
    "dghfgsyiznoumknlxgvacpwqtr"
    "jghfbeyiznkumkjlxevacpwqtr"
    "daofbsyiznoumkjlxevampwqtr"
    "dghfbsyiznojmkjlxeracpcqtr"
    "dghnbsyiznouokjlxevaclwqtr"
    "dgifbsyiznoumkjlxevnspwqtr"
    "dgkfpsziznoumkjlxevacpwqtr"
    "dghfxsyijnoumkjlxevaccwqtr"
    "dghfbsyiznolmkjlwevzcpwqtr"
    "dkhfbsaiznoumkjlxevacpwqtg"
    "dghfbsygknoumkjlaevacpwqtr"
    "dghfbsyizizumkjlxevacpxqtr"
    "ighfbbyijnoumxjlxevacpwqtr"
    "dghfbsyizrouekjlxevacpwktr"
    "dghobsyiznoujkjlxevacnwqtr"
    "dghpbsyizyoumkjlxeaacpwqtr"
    "dghffsyiznoymkjlxevacewqtr"
    "dghkbssiznoumzjlxevacpwqtr"
    "dghfbsyawnoumkjlxevacpwjtr"
    "drhfbsyiznormkjlfevacpwqtr"
    "dghfbsoiznouwkjlxevacpwqtn"
    "dghfmsyiznoumkjlxlvecpwqtr"
    "dxhfbsyiznoumkjlxeeacvwqtr"
    "dghnbsyiznoumkjsxevacpwqur"
    "dghfbsyiznrujkjlxevacpwqtc"
    "dghfbstoznoumhjlxevacpwqtr"
    "dghfboyiznzumkjlvevacpwqtr"
    "dghfbsyiznjumkjlxevgcpwmtr"
    "dghfbsnizaoumkjlxevacpwetr"
    "dghfbsyirnoumkjoxevacplqtr"
    "dghfbsyiznoumkjlxavvckwqtr"
    "dghfbjdiznoumkjlxevacpwptr"
    "dghfbsywznoumkjlxeiacpwqcr"
    "djhfbsyizuoumkjlxelacpwqtr"
    "dghffsniznoumkjlxpvacpwqtr"
    "dghebsyizuoumkjlxevecpwqtr"
    "rghfbsyiznourkjcxevacpwqtr"
    "dghfbsyignoumkwlxenacpwqtr"
    "dghfbsyiznrufkjlxevacpwqth"
    "dgifbsyiznoumkjlxevacpjqnr"
    "dghfbsyiznoumkjbxevaxpwqtw"
    "dsufbsyizncumkjlxevacpwqtr"
    "dihfbsyiznoumujlxecacpwqtr"
    "dghfbiyiznoumkjlxevajpwqtn"
    "dghqbsyixnoumkjlrevacpwqtr"
    "dghfbsyiznouukjlxeuacpwqtx"
    "dghfbsyizyoumksfxevacpwqtr"
    "dghfbsiiznopfkjlxevacpwqtr"
    "eghfbsyidnoumkjlxexacpwqtr"
    "dghfbgyiznouwkjlwevacpwqtr"
    "dghfbsyyznoumkjlxevacwwqtf"
    "bghfbtypznoumkjlxevacpwqtr"
    "dghfbsyiznoumtjlxebacpwetr"
    "dghfbsgiznonmkplxevacpwqtr"
    "dghfbsyiznoumxjlxevanpwqpr"
    "dghfbsyiznwumujuxevacpwqtr"
    "dghxbsyiznoumkjzxevaypwqtr"
    "dghfbsyhznoumkjlxlvacpiqtr"
    "dghfbsyiznoumkjlxevzcnwqrr"
    "dvhfbsyiznoumkjluevacpzqtr"
    "dghcbsyiznoumkjlxmvacpwetr"
    "dghfbsyiznohmkjvxbvacpwqtr"
    "dghfzsyiznouokjlxevacpwqpr"
    "dghfbsyiznoumkjlxevachtqth"
    "dghfbsyiznoumkjlxjvacpfutr"
    "dghfbsyiznoumkjlxevsppwqtt"
    "dghfusyiznouakhlxevacpwqtr"
    "dghfbsyizcoumkjlxrvaipwqtr"
    "dghebsyipnoumfjlxevacpwqtr"
    "dgdfbsyiznoumkjlwevacpkqtr"
    "dghfbsyiznoumkjlcffacpwqtr"
    "dghfbsypznfumkjlxevacpwqar"
    "dghfbsyiznojmkjlxevgcpkqtr"
    "dghfbsyiznoumkjlaevlcpwstr"
    "dgafrsyiunoumkjlxevacpwqtr"
    "dghfbsyiznouqljlxevacrwqtr"
    "dyhkbsyiznokmkjlxevacpwqtr"
    "pghfbsciznoumkjlxevacpwvtr"
    "dghfbxyiznonmkjllevacpwqtr"
    "ighfbsyizxoumkjlxevacpzqtr"
    "dgffbsyoznoumkjlxevacpwqto"
    "hghfbsyiznoumkjlpevachwqtr"
    "dlhfosyiznoumkjldevacpwqtr"
    "dghfbsvizkoumkjlxvvacpwqtr"
    "dbafbsyiznozmkjlxevacpwqtr"
    "dghfbsyidnoumkjlxrvjcpwqtr"
    "dghfbsyiznfumkjlxeqacpwqta"
    "dghfbsfiznoumkjvxevacjwqtr"
    "dghfbsyimnoumrjlhevacpwqtr"
    "dghflsyiznoumkjlxevacpvqmr"
    "dghfbmfiznoumkjlxevacpdqtr"
    "dghfbsyizsouzkjlxevscpwqtr"
    "dghfksyiznoumimlxevacpwqtr"
    "dghfbsyiznoumkjlxevbwpwqur"
    "wghcbsyiznoumkjlkevacpwqtr"
    "kghfbioiznoumkjlxevacpwqtr"
    "dghfbsiizeoumkjlxmvacpwqtr"
    "dglfbsyilnoumkjlxevpcpwqtr"
    "dgqfbsylznoumkjlxevacpwqcr"
    "dglfhsyiznoumkjlxevacpwqdr"
    "dghfbsymznoumkjlxbvacpwqtb"
    "hghfbsyizhoumkjlxtvacpwqtr"
    "dghdbsyiznoumkjlxeiacpyqtr"
    "dohfbsyiznoumkjmxlvacpwqtr"
    "xhhfbsyiznoumkjlxegacpwqtr"
    "dlhfbsyiznoumkjlxnvahpwqtr"
    "dghfbsyiznovdpjlxevacpwqtr"
    "dgcfbsyiznoumkjlxevactwqdr"
    "dghfksyiknoumkjlxevacpwqcr"
    "ughfqsyiznoumkjlxevacpwctr"
    "dghfbjyiznoumkjlxsvacnwqtr"
    "dgwfbagiznoumkjlxevacpwqtr"
    "dghfbsyiznoumknlxevtcpwqdr"
    "jghfksyiznoumkjlxeoacpwqtr"
    "dghfbsyiznoimkjlwezacpwqtr"
    "dghfbsyiunoumkjlxeqacpwstr"
    "dghfbsyizjoumkwlxevaypwqtr"
    "dghfysriznoumkjlxevucpwqtr"
    "dghfbsygzjoumkjfxevacpwqtr"
    "dghfbhviznoumkjlxevacpwqtq"
    "dghfbsyiznoumkjvwevacpwqur"
    "dghfbsyiznoumtjlxevacplqnr"
    "yghfbsysznouykjlxevacpwqtr"
    "dgwfbsiiznoumkjlxevacfwqtr"
    "dghfbsyizooumkjlxevampiqtr"
    "dshfbsyiznoumkjlxevawpoqtr"
    "dghtbsyxznuumkjlxevacpwqtr"
    "dkhfblyiznoumkjlxevacpaqtr"
    "dgkfbsyiinoumkjlxegacpwqtr"
    "dghfbtxiznouhkjlxevacpwqtr"
    "dghfbsyiznoumkjlxkvmcpeqtr"
    "dghfbsyiznoumkjlghvacpwqmr"
    "dghfbsbizioumkjlcevacpwqtr"
    "dphfbsyizhoumkjwxevacpwqtr"
    "dghfbsyiznqumkjlugvacpwqtr"
    "dghfbsjinnoumkjlxevacpwetr"
    "mghfbsyiznoumkjlxfvacpjqtr"
    "dghfbsxiznoumkjlxetacwwqtr"
    "dghmbsyiznoumbjlxevacpwqyr"
    "dghfbsyiznwumkjlwevacmwqtr"
    "dgkfbsyiznotmkjlxevacpwstr"
    "dghfbsyiznouykjlxeiacuwqtr"
    "dghfbsynznbhmkjlxevacpwqtr"
    "dgyfbsyiznoumtjlbevacpwqtr"
    "dghfbftiznoumkjlxevacpwatr"
    "dghfvsyiznouikjlievacpwqtr"
    "dghfbsyiznodmkjlxevncpwqtz"
    "yfhfbsyiznoumkjluevacpwqtr"
    "dghfbzyiznoumhflxevacpwqtr"
    "dphfbsyizncumkjlxevacpwqtf"
    "dghfasyiznoumkjlxeaicpwqtr"
    "dgffbsyiznoumkjlzevacpwqsr"
    "dghfbsyiznoumkmxxcvacpwqtr"
    "dghffsyiznoumkjlxevacpwqre"
    "dghfbsyizndmmkjlxemacpwqtr"
    "dghfbsviznoamkjlxevappwqtr"
    "dghfbsyiznouckrlxevacpdqtr"
    "dgwfbsyiznyumkjlxevacpqqtr"
    "dujfbsyiznoumgjlxevacpwqtr"
    "dghobsailnoumkjlxevacpwqtr"
    "dghfkqyiznoumknlxevacpwqtr"
    "dghfbyypznoumkjlxevacpwatr"
    "wqhfbsyiznoumkjlxevzcpwqtr"
    "dghfbsyiznoumwjlxrvacppqtr"
    "dghfbsymznoumkflxevacplqtr"
    "dghfbsyiznounkjpgevacpwqtr"
    "ighfbsyijnoumxjlxevacpwqtr"
    "dghfbsyizroumkjllevncpwqtr"
    "dghfbsliznokmkjlxevacpwqtb"
    "dgefbsyiznoumkqlxevpcpwqtr"
    "dghfbtypznouzkjlxevacpwqtr"
    "dmhfbsyiznoumkjlxeyactwqtr"
    "vohfbsyiznoumkjlqevacpwqtr"
    "dgsfpsyiznodmkjlxevacpwqtr"
    "dghfzsyijnoumkjnxevacpwqtr"
    "dghfbayijroumkjlxevacpwqtr"
    "dghfbsyiznodmxjlxgvacpwqtr"
    "dghfbsyiznocmkjlxhvaipwqtr"
    "dghmbsyignoumkjlxevacpoqtr"
    "dghfbsyiznosmkjlncvacpwqtr"
    "dggfbsyiznuumkjlxevacpwqrr"
    "dghibsyilnoumkjlxevacowqtr"
    "dghfbsyiznoumkjluevbcowqtr"
    "dghfbsaiznyuvkjlxevacpwqtr"
    "dgnfxsyiznommkjlxevacpwqtr"
    "dghfbnyiznoumkjlsnvacpwqtr"
    "dghfssiiznoumkjlxavacpwqtr"
    "dghfbsyizneumajlxevacfwqtr"
    "dghfbsyiznoumkjlxevycpvptr"
    "qghfbsyizgoumkjlxevacpwttr"
    "vghfbsyiznoumkjlievaepwqtr"
    "dghfbsyiznoumejlxjvacpwdtr"
    "dghfbsyispoumkjlxevacpwqtg"
    "duhfbsyizpoumkjlxenacpwqtr"
    "dghfbsyifnoumkblxevacpnqtr"
    "bghfbsyxznoumkjleevacpwqtr"
    "dgtfbsyzpnoumkjlxevacpwqtr"
    "dghfbsyiznoumkjlsecacpwqth"
    "dghfqsyiznjumkjlxevawpwqtr"
    "dgcfbsyizboumkjlxevacqwqtr"
    "dghfbqyiznoumkjkxevacpwqtj"
    "dgyfbsyfznoumkjlievacpwqtr"
    "dghfdsyiznoumkplxevacpwdtr"
    "dphfbsyuznkumkjlxevacpwqtr"
    "dghfbsyiznoupkjitevacpwqtr"
    "dghfisyiznoamkjlxevacpwqwr"
    "dgufbsyiznoumkjlxivvcpwqtr"
    "dghfbvyiznoumkjlxevacvwqtz"
    "dghfbsyiqnxumkjlxbvacpwqtr"
    "dghubsyiznqumkflxevacpwqtr"
    "dghfbsyiznzumkjlxevacpdbtr"
    "dghfbsyiznoumkjlxehacpwwrr"
    "mghfbsyiznoumkjlxevacpwqbp"
    "dvhfbryiznoumkclxevacpwqtr"
    "dghbbsyiznotmkjlxevacpwqhr"
    "dghfrsyiznoomkjlxevacpwqto"
    "dghfbkyiznoumkjlxeracpxqtr"
    "dghfbfyizfoumkjlxevacpwjtr"
    "dghfbsyizqoulkjlxevacpwqtt"
    "dghfbsyiwnoumkjlxevacxwgtr"
    "dghfbsyiznormkjlgxvacpwqtr"
    "dghybsyizioumkjoxevacpwqtr"
    "dchfbsyiznoumkjlxyvacpwqtc"
    "dgyfbsyiznouckjlxewacpwqtr"
    "dakfbsyeznoumkjlxevacpwqtr"))
